-- ============================================================================
-- Migration 0105: ECHT zaalplan CC Ter Dilft Bornem (vervangt oude versie)
-- Date: 2026-06-28
-- Description: Vervangt het zaalplan voor CC Ter Dilft Bornem met de échte
-- layout zoals afgebeeld op de officiële zaalfoto:
--   • 19 rijen A→S (rij I ontbrak in vorige versie)
--   • Rij A-F: doorlopende middensectie (geen Oneven/Even splitsing vooraan)
--   • Rij G-S: midden + zijvleugels (zijvleugels GROEIEN van 2→6 per kant)
--   • Rij P: 3 VIP-stoelen in het midden (markeerbaar via category_id)
--   • Rij Q: 8 rolstoelplaatsen midden (type='wheelchair')
--   • Rij I: 1 begeleidersplaats rechts (type='companion')
--   • Rij B, H, S: geblokkeerde stoelen (status='blocked') zoals op foto
--   • Oneven/Even nummering behouden (1,3,5... links / 2,4,6... rechts)
--   • Gebogen waaiervorm via lichte x/y curve-correctie
--
-- VEILIG: bij stand 2026-06-28 zijn er 0 verkochte ticket_seats voor dit plan
-- (gecheckt via 'SELECT COUNT(*) FROM ticket_seats ts JOIN seats s ON s.id=ts.seat_id
--  WHERE s.plan_id = (SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem')'
--  → 0). Geen actief concert gebruikt dit plan (alleen concert 7 → plan 1).
--
-- IDEMPOTENT: DELETE+INSERT pattern. Bij herstart wordt het plan volledig
-- opnieuw opgebouwd. Geen impact op seating_plans-row zelf (UPDATE op naam/desc).
-- ============================================================================

-- Update plan metadata
UPDATE seating_plans
SET description = 'Schouwburg CC Ter Dilft Bornem — gebogen waaiervorm volgens officiële zaalfoto. 19 rijen A-S, doorlopende middensectie vooraan (rij A-F), zijvleugels groeiend in rij G-S, 8 rolstoelplaatsen op rij Q, 1 begeleidersplaats rij I, 3 VIP-stoelen rij P.',
    width = 1100,
    height = 800
WHERE name = 'CC Ter Dilft Bornem';

-- Verwijder oude stoelen
DELETE FROM seats WHERE plan_id = (SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem');

-- Nieuwe stoelen (gegenereerd door scripts/gen_ter_dilft_plan.py)

-- Rij A (0 links + 12 midden + 0 rechts = 12 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'A', '1', 537, 220, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'A', '3', 511, 219, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'A', '5', 485, 218, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'A', '7', 459, 216, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'A', '9', 433, 213, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'A', '11', 407, 210, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'A', '2', 563, 220, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'A', '4', 589, 219, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'A', '6', 615, 218, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'A', '8', 641, 216, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'A', '10', 667, 213, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'A', '12', 693, 210, 'standard', 'available');

-- Rij B (0 links + 19 midden + 0 rechts = 19 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '1', 537, 248, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '3', 511, 247, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '5', 485, 246, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '7', 459, 244, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '9', 433, 241, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '11', 407, 238, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '13', 381, 234, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '15', 355, 229, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '17', 329, 224, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '19', 303, 217, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '2', 563, 248, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '4', 589, 247, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '6', 615, 246, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '8', 641, 244, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '10', 667, 241, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '12', 693, 238, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '14', 719, 234, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '16', 745, 229, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'B', '18', 771, 224, 'standard', 'blocked');

-- Rij C (0 links + 18 midden + 0 rechts = 18 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '1', 537, 276, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '3', 511, 275, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '5', 485, 274, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '7', 459, 272, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '9', 433, 269, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '11', 407, 266, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '13', 381, 262, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '15', 355, 257, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '17', 329, 252, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '2', 563, 276, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '4', 589, 275, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '6', 615, 274, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '8', 641, 272, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '10', 667, 269, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '12', 693, 266, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '14', 719, 262, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '16', 745, 257, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'C', '18', 771, 252, 'standard', 'available');

-- Rij D (0 links + 18 midden + 0 rechts = 18 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '1', 537, 304, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '3', 511, 303, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '5', 485, 302, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '7', 459, 300, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '9', 433, 297, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '11', 407, 294, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '13', 381, 290, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '15', 355, 285, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '17', 329, 280, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '2', 563, 304, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '4', 589, 303, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '6', 615, 302, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '8', 641, 300, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '10', 667, 297, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '12', 693, 294, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '14', 719, 290, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '16', 745, 285, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'D', '18', 771, 280, 'standard', 'available');

-- Rij E (0 links + 20 midden + 0 rechts = 20 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '1', 537, 332, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '3', 511, 331, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '5', 485, 330, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '7', 459, 328, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '9', 433, 325, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '11', 407, 322, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '13', 381, 318, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '15', 355, 313, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '17', 329, 308, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '19', 303, 301, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '2', 563, 332, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '4', 589, 331, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '6', 615, 330, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '8', 641, 328, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '10', 667, 325, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '12', 693, 322, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '14', 719, 318, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '16', 745, 313, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '18', 771, 308, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'E', '20', 797, 301, 'standard', 'available');

-- Rij F (0 links + 20 midden + 0 rechts = 20 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '1', 537, 360, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '3', 511, 359, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '5', 485, 358, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '7', 459, 356, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '9', 433, 353, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '11', 407, 350, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '13', 381, 346, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '15', 355, 341, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '17', 329, 336, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '19', 303, 329, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '2', 563, 360, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '4', 589, 359, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '6', 615, 358, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '8', 641, 356, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '10', 667, 353, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '12', 693, 350, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '14', 719, 346, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '16', 745, 341, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '18', 771, 336, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'F', '20', 797, 329, 'standard', 'available');

-- Rij G (2 links + 22 midden + 2 rechts = 26 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '1', 537, 388, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '3', 511, 387, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '5', 485, 386, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '7', 459, 384, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '9', 433, 381, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '11', 407, 378, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '13', 381, 374, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '15', 355, 369, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '17', 329, 364, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '19', 303, 357, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '21', 277, 351, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '2', 563, 388, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '4', 589, 387, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '6', 615, 386, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '8', 641, 384, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '10', 667, 381, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '12', 693, 378, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '14', 719, 374, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '16', 745, 369, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '18', 771, 364, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '20', 797, 357, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'G', '22', 823, 351, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'G', '1', 240, 340, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'G', '3', 214, 332, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'G', '2', 860, 340, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'G', '4', 886, 332, 'standard', 'available');

-- Rij H (3 links + 22 midden + 3 rechts = 28 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '1', 537, 416, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '3', 511, 415, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '5', 485, 414, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '7', 459, 412, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '9', 433, 409, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '11', 407, 406, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '13', 381, 402, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '15', 355, 397, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '17', 329, 392, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '19', 303, 385, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '21', 277, 379, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '2', 563, 416, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '4', 589, 415, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '6', 615, 414, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '8', 641, 412, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '10', 667, 409, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '12', 693, 406, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '14', 719, 402, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '16', 745, 397, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '18', 771, 392, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '20', 797, 385, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'H', '22', 823, 379, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'H', '1', 240, 368, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'H', '3', 214, 360, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'H', '5', 188, 350, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'H', '2', 860, 368, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'H', '4', 886, 360, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'H', '6', 912, 350, 'standard', 'blocked');

-- Rij I (3 links + 22 midden + 4 rechts = 29 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '1', 537, 444, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '3', 511, 443, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '5', 485, 442, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '7', 459, 440, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '9', 433, 437, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '11', 407, 434, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '13', 381, 430, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '15', 355, 425, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '17', 329, 420, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '19', 303, 413, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '21', 277, 407, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '2', 563, 444, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '4', 589, 443, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '6', 615, 442, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '8', 641, 440, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '10', 667, 437, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '12', 693, 434, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '14', 719, 430, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '16', 745, 425, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '18', 771, 420, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '20', 797, 413, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'I', '22', 823, 407, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'I', '1', 240, 396, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'I', '3', 214, 388, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'I', '5', 188, 378, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'I', '2', 860, 396, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'I', '4', 886, 388, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'I', '6', 912, 378, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'I', '8', 938, 369, 'companion', 'available');

-- Rij J (4 links + 22 midden + 4 rechts = 30 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '1', 537, 472, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '3', 511, 471, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '5', 485, 470, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '7', 459, 468, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '9', 433, 465, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '11', 407, 462, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '13', 381, 458, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '15', 355, 453, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '17', 329, 448, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '19', 303, 441, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '21', 277, 435, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '2', 563, 472, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '4', 589, 471, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '6', 615, 470, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '8', 641, 468, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '10', 667, 465, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '12', 693, 462, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '14', 719, 458, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '16', 745, 453, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '18', 771, 448, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '20', 797, 441, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'J', '22', 823, 435, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'J', '1', 240, 424, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'J', '3', 214, 416, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'J', '5', 188, 406, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'J', '7', 162, 397, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'J', '2', 860, 424, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'J', '4', 886, 416, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'J', '6', 912, 406, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'J', '8', 938, 397, 'standard', 'available');

-- Rij K (4 links + 22 midden + 4 rechts = 30 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '1', 537, 500, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '3', 511, 499, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '5', 485, 498, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '7', 459, 496, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '9', 433, 493, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '11', 407, 490, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '13', 381, 486, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '15', 355, 481, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '17', 329, 476, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '19', 303, 469, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '21', 277, 463, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '2', 563, 500, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '4', 589, 499, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '6', 615, 498, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '8', 641, 496, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '10', 667, 493, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '12', 693, 490, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '14', 719, 486, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '16', 745, 481, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '18', 771, 476, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '20', 797, 469, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'K', '22', 823, 463, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'K', '1', 240, 452, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'K', '3', 214, 444, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'K', '5', 188, 434, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'K', '7', 162, 425, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'K', '2', 860, 452, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'K', '4', 886, 444, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'K', '6', 912, 434, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'K', '8', 938, 425, 'standard', 'available');

-- Rij L (5 links + 22 midden + 5 rechts = 32 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '1', 537, 528, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '3', 511, 527, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '5', 485, 526, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '7', 459, 524, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '9', 433, 521, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '11', 407, 518, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '13', 381, 514, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '15', 355, 509, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '17', 329, 504, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '19', 303, 497, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '21', 277, 491, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '2', 563, 528, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '4', 589, 527, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '6', 615, 526, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '8', 641, 524, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '10', 667, 521, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '12', 693, 518, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '14', 719, 514, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '16', 745, 509, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '18', 771, 504, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '20', 797, 497, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'L', '22', 823, 491, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'L', '1', 240, 480, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'L', '3', 214, 472, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'L', '5', 188, 462, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'L', '7', 162, 453, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'L', '9', 136, 442, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'L', '2', 860, 480, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'L', '4', 886, 472, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'L', '6', 912, 462, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'L', '8', 938, 453, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'L', '10', 964, 442, 'standard', 'available');

-- Rij M (5 links + 22 midden + 5 rechts = 32 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '1', 537, 556, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '3', 511, 555, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '5', 485, 554, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '7', 459, 552, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '9', 433, 549, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '11', 407, 546, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '13', 381, 542, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '15', 355, 537, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '17', 329, 532, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '19', 303, 525, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '21', 277, 519, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '2', 563, 556, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '4', 589, 555, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '6', 615, 554, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '8', 641, 552, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '10', 667, 549, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '12', 693, 546, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '14', 719, 542, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '16', 745, 537, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '18', 771, 532, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '20', 797, 525, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'M', '22', 823, 519, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'M', '1', 240, 508, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'M', '3', 214, 500, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'M', '5', 188, 490, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'M', '7', 162, 481, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'M', '9', 136, 470, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'M', '2', 860, 508, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'M', '4', 886, 500, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'M', '6', 912, 490, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'M', '8', 938, 481, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'M', '10', 964, 470, 'standard', 'available');

-- Rij N (5 links + 22 midden + 5 rechts = 32 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '1', 537, 584, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '3', 511, 583, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '5', 485, 582, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '7', 459, 580, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '9', 433, 577, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '11', 407, 574, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '13', 381, 570, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '15', 355, 565, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '17', 329, 560, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '19', 303, 553, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '21', 277, 547, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '2', 563, 584, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '4', 589, 583, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '6', 615, 582, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '8', 641, 580, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '10', 667, 577, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '12', 693, 574, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '14', 719, 570, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '16', 745, 565, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '18', 771, 560, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '20', 797, 553, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'N', '22', 823, 547, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'N', '1', 240, 536, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'N', '3', 214, 528, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'N', '5', 188, 518, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'N', '7', 162, 509, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'N', '9', 136, 498, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'N', '2', 860, 536, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'N', '4', 886, 528, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'N', '6', 912, 518, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'N', '8', 938, 509, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'N', '10', 964, 498, 'standard', 'available');

-- Rij O (6 links + 22 midden + 6 rechts = 34 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '1', 537, 612, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '3', 511, 611, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '5', 485, 610, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '7', 459, 608, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '9', 433, 605, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '11', 407, 602, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '13', 381, 598, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '15', 355, 593, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '17', 329, 588, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '19', 303, 581, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '21', 277, 575, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '2', 563, 612, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '4', 589, 611, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '6', 615, 610, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '8', 641, 608, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '10', 667, 605, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '12', 693, 602, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '14', 719, 598, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '16', 745, 593, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '18', 771, 588, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '20', 797, 581, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'O', '22', 823, 575, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'O', '1', 240, 564, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'O', '3', 214, 556, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'O', '5', 188, 546, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'O', '7', 162, 537, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'O', '9', 136, 526, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'O', '11', 110, 515, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'O', '2', 860, 564, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'O', '4', 886, 556, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'O', '6', 912, 546, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'O', '8', 938, 537, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'O', '10', 964, 526, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'O', '12', 990, 515, 'standard', 'available');

-- Rij P (6 links + 22 midden + 6 rechts = 34 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '1', 537, 640, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '3', 511, 639, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '5', 485, 638, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '7', 459, 636, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '9', 433, 633, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '11', 407, 630, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '13', 381, 626, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '15', 355, 621, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '17', 329, 616, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '19', 303, 609, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '21', 277, 603, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '2', 563, 640, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '4', 589, 639, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '6', 615, 638, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '8', 641, 636, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '10', 667, 633, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '12', 693, 630, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '14', 719, 626, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '16', 745, 621, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '18', 771, 616, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '20', 797, 609, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'P', '22', 823, 603, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'P', '1', 240, 592, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'P', '3', 214, 584, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'P', '5', 188, 574, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'P', '7', 162, 565, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'P', '9', 136, 554, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'P', '11', 110, 543, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'P', '2', 860, 592, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'P', '4', 886, 584, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'P', '6', 912, 574, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'P', '8', 938, 565, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'P', '10', 964, 554, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'P', '12', 990, 543, 'standard', 'available');

-- Rij Q (6 links + 22 midden + 6 rechts = 34 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '1', 537, 668, 'wheelchair', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '3', 511, 667, 'wheelchair', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '5', 485, 666, 'wheelchair', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '7', 459, 664, 'wheelchair', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '9', 433, 661, 'wheelchair', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '11', 407, 658, 'wheelchair', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '13', 381, 654, 'wheelchair', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '15', 355, 649, 'wheelchair', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '17', 329, 644, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '19', 303, 637, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '21', 277, 631, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '2', 563, 668, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '4', 589, 667, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '6', 615, 666, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '8', 641, 664, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '10', 667, 661, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '12', 693, 658, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '14', 719, 654, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '16', 745, 649, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '18', 771, 644, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '20', 797, 637, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'Q', '22', 823, 631, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'Q', '1', 240, 620, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'Q', '3', 214, 612, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'Q', '5', 188, 602, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'Q', '7', 162, 593, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'Q', '9', 136, 582, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'Q', '11', 110, 571, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'Q', '2', 860, 620, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'Q', '4', 886, 612, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'Q', '6', 912, 602, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'Q', '8', 938, 593, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'Q', '10', 964, 582, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'Q', '12', 990, 571, 'standard', 'available');

-- Rij R (6 links + 22 midden + 6 rechts = 34 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '1', 537, 696, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '3', 511, 695, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '5', 485, 694, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '7', 459, 692, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '9', 433, 689, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '11', 407, 686, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '13', 381, 682, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '15', 355, 677, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '17', 329, 672, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '19', 303, 665, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '21', 277, 659, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '2', 563, 696, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '4', 589, 695, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '6', 615, 694, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '8', 641, 692, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '10', 667, 689, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '12', 693, 686, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '14', 719, 682, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '16', 745, 677, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '18', 771, 672, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '20', 797, 665, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'R', '22', 823, 659, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'R', '1', 240, 648, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'R', '3', 214, 640, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'R', '5', 188, 630, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'R', '7', 162, 621, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'R', '9', 136, 610, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'R', '11', 110, 599, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'R', '2', 860, 648, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'R', '4', 886, 640, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'R', '6', 912, 630, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'R', '8', 938, 621, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'R', '10', 964, 610, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'R', '12', 990, 599, 'standard', 'available');

-- Rij S (6 links + 22 midden + 6 rechts = 34 stoelen)
INSERT INTO seats (plan_id, section_name, row_label, seat_number, x, y, type, status) VALUES
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '1', 537, 724, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '3', 511, 723, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '5', 485, 722, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '7', 459, 720, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '9', 433, 717, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '11', 407, 714, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '13', 381, 710, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '15', 355, 705, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '17', 329, 700, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '19', 303, 693, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '21', 277, 687, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '2', 563, 724, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '4', 589, 723, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '6', 615, 722, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '8', 641, 720, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '10', 667, 717, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '12', 693, 714, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '14', 719, 710, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '16', 745, 705, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '18', 771, 700, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '20', 797, 693, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Midden', 'S', '22', 823, 687, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'S', '1', 240, 676, 'standard', 'available'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'S', '3', 214, 668, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'S', '5', 188, 658, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'S', '7', 162, 649, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'S', '9', 136, 638, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Links', 'S', '11', 110, 627, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'S', '2', 860, 676, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'S', '4', 886, 668, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'S', '6', 912, 658, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'S', '8', 938, 649, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'S', '10', 964, 638, 'standard', 'blocked'),
  ((SELECT id FROM seating_plans WHERE name = 'CC Ter Dilft Bornem'), 'Zijvleugel Rechts', 'S', '12', 990, 627, 'standard', 'available');

-- VIP-stoelen (rij P midden, nrs 1/2/3) — markeer via comment.
-- (Echte category_id wordt later via admin gekoppeld zodra prijscategorieën bestaan.)
-- Identificeerbaar via: SELECT id FROM seats WHERE plan_id=(SELECT id FROM seating_plans WHERE name='CC Ter Dilft Bornem') AND row_label='P' AND section_name='Midden' AND seat_number IN ('1','2','3');

-- Totaal: 516 stoelen | 22 blocked | 8 rolstoel | 1 companion | 3 VIP